main: eu.octanne.survivalclaims.SurvivalClaim
name: SurvivalClaims
author: Octanne
version: 2.5
depends: [Vault, WorldGuard]
description: claim system area for player.
commands:
  claim:
    description: a main command
